#!/usr/bin/env python3
"""
OpenAPI to ahttp_client Package Generator
CLI tool that generates a complete Python package from an OpenAPI Specification.
"""

import argparse
import ast
import json
import os
import pathlib
from typing import Dict, Any

from core.loader import load_spec
from parser.extractor import OpenAPIExtractor
from generator.models import ModelsGenerator
from generator.client import ClientGenerator
from generator.package_init import PackageInitGenerator
from generator.exceptions import ExceptionsGenerator
from generator.http import HTTPGenerator


def write_ast_to_file(file_path: str, module_ast: ast.Module) -> None:
    """Convert AST module to Python code and write to file with PEP 8 formatting."""
    try:
        # Use Python 3.9+ ast.unparse
        code = ast.unparse(module_ast)

        # Apply PEP 8 formatting
        code = apply_pep8_formatting(code)

    except AttributeError:
        # For older Python versions, compile and exec the AST to validate,
        # then write a basic version
        try:
            compile(module_ast, '<generated>', 'exec')
            # Simple fallback - this should work for most cases
            code = "# -*- coding: utf-8 -*-\n"
            code += '"""\nThis code was automatically generated by the OpenAPI Generator.\nDo not modify this file directly, as any changes will be overwritten \nwhen the code is regenerated.\n"""\n\n'
            code += "# Generated code - requires Python 3.9+ for proper formatting\n"
            code += "# Please upgrade Python or install 'astor' package for better output\n\n"

            # Extract imports and classes manually
            for node in module_ast.body:
                if isinstance(node, ast.ImportFrom):
                    if node.level > 0:
                        code += f"from {'.' * node.level}{node.module or ''} import "
                    else:
                        code += f"from {node.module} import "
                    code += ", ".join(alias.name for alias in node.names) + "\n"
                elif isinstance(node, ast.Import):
                    code += f"import {', '.join(alias.name for alias in node.names)}\n"
                elif isinstance(node, ast.ClassDef):
                    bases = ", ".join(base.id if hasattr(base, 'id') else str(base) for base in node.bases)
                    code += f"\n\nclass {node.name}({bases}):\n    pass  # Implementation generated\n"
                elif isinstance(node, ast.FunctionDef):
                    code += f"\n\ndef {node.name}():\n    pass  # Implementation generated\n"

            # Ensure file ends with newline
            code += "\n"

        except Exception as e:
            raise RuntimeError(f"Failed to process AST: {e}")

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(code)


def apply_pep8_formatting(code: str) -> str:
    """Apply PEP 8 formatting rules to generated code."""
    lines = code.split('\n')

    # Start with encoding header and docstring
    result_lines = [
        '# -*- coding: utf-8 -*-',
        '"""',
        'This code was automatically generated by the OpenAPI Generator.',
        'Do not modify this file directly, as any changes will be overwritten',
        'when the code is regenerated.',
        '"""'
    ]

    # Skip any existing docstring/header content
    start_idx = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if (stripped.startswith(('"""', "'''")) and
            ('This code was automatically generated' in stripped or
             'Do not modify this file' in stripped)):
            # Find the end of this docstring block
            quote_type = stripped[:3]
            for j in range(i + 1, len(lines)):
                if quote_type in lines[j] or 'when the code is regenerated' in lines[j]:
                    start_idx = j + 1
                    break
            break
        elif stripped.startswith('"""') or stripped.startswith("'''"):
            # Skip other docstrings
            continue
        elif stripped:
            start_idx = i
            break

    # Process imports and rest of the code
    imports = []
    rest_content = []
    in_import_section = True

    for i in range(start_idx, len(lines)):
        line = lines[i]
        stripped = line.strip()

        if stripped.startswith(('import ', 'from ')):
            if in_import_section:
                imports.append(line)
            else:
                rest_content.append(line)
        elif stripped.startswith('__all__'):
            in_import_section = False
            rest_content.append(line)
        elif stripped == '':
            # Only add blank line if we're not in import section or if there's content after
            if not in_import_section:
                rest_content.append(line)
        else:
            in_import_section = False
            rest_content.append(line)

    # Add imports to result
    if imports:
        result_lines.append('')  # Blank line after docstring
        result_lines.extend(imports)

    # Add rest of content
    if rest_content:
        result_lines.append('')  # Blank line after imports
        result_lines.extend(rest_content)

    # Clean up multiple blank lines and ensure proper spacing
    final_lines = []
    prev_line_empty = False

    for line in result_lines:
        is_empty = not line.strip()

        # Add 2 blank lines before class definitions
        if line.strip().startswith('class ') and final_lines:
            # Remove any existing blank lines
            while final_lines and not final_lines[-1].strip():
                final_lines.pop()
            # Add exactly 2 blank lines
            final_lines.extend(['', ''])
            final_lines.append(line)
            prev_line_empty = False

        # Add blank line before __all__ if needed
        elif line.strip().startswith('__all__') and final_lines and final_lines[-1].strip():
            final_lines.append('')
            final_lines.append(line)
            prev_line_empty = False

        # Skip multiple consecutive blank lines
        elif is_empty and prev_line_empty:
            continue

        else:
            final_lines.append(line)
            prev_line_empty = is_empty

    # Ensure exactly one newline at end
    while final_lines and not final_lines[-1].strip():
        final_lines.pop()
    final_lines.append('')

    return '\n'.join(final_lines)


def main():
    parser = argparse.ArgumentParser(
        description='Generate Python package from OpenAPI specification'
    )
    parser.add_argument('input_file', help='Path to OpenAPI specification file (JSON, YAML, or XML)')
    parser.add_argument('output_dir', help='Output directory name for generated package')

    args = parser.parse_args()

    # Load and parse OpenAPI specification
    print(f"Loading OpenAPI specification from {args.input_file}")
    spec_data = load_spec(args.input_file)

    print("Extracting OpenAPI components")
    extractor = OpenAPIExtractor()
    extracted_data = extractor.extract(spec_data)

    # Generate AST modules
    print("Generating model files")
    models_generator = ModelsGenerator()
    model_modules, model_names = models_generator.generate(extracted_data)

    print("Generating exception files")
    exceptions_generator = ExceptionsGenerator()
    exception_modules = exceptions_generator.generate(extracted_data)

    print("Generating http.py")
    http_generator = HTTPGenerator()
    http_ast = http_generator.generate(extracted_data, model_names)

    print("Generating client.py")
    client_generator = ClientGenerator()
    client_ast = client_generator.generate(extracted_data, model_names)

    print("Generating __init__.py")
    init_generator = PackageInitGenerator()
    init_ast = init_generator.generate(extracted_data, model_names)

    # Create output directory and write files
    output_path = pathlib.Path(args.output_dir)
    output_path.mkdir(exist_ok=True)

    print(f"Writing package files to {output_path}")

    # Create models directory and write model files
    models_dir = output_path / 'models'
    models_dir.mkdir(exist_ok=True)

    for filename, module_ast in model_modules.items():
        model_file = models_dir / filename
        write_ast_to_file(str(model_file), module_ast)
        print(f"  ✓ {model_file}")

    # Create exceptions directory and write exception files
    if exception_modules:
        exceptions_dir = output_path / 'exceptions'
        exceptions_dir.mkdir(exist_ok=True)

        for filename, module_ast in exception_modules.items():
            exception_file = exceptions_dir / filename
            write_ast_to_file(str(exception_file), module_ast)
            print(f"  ✓ {exception_file}")

    # Write http.py
    http_file = output_path / 'http.py'
    write_ast_to_file(str(http_file), http_ast)
    print(f"  ✓ {http_file}")

    # Write client.py
    client_file = output_path / 'client.py'
    write_ast_to_file(str(client_file), client_ast)
    print(f"  ✓ {client_file}")

    # Write __init__.py
    init_file = output_path / '__init__.py'
    write_ast_to_file(str(init_file), init_ast)
    print(f"  ✓ {init_file}")

    print(f"\n✨ Package '{args.output_dir}' generated successfully!")
    print(f"   You can now use: from {args.output_dir} import *")


if __name__ == '__main__':
    main()


